FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

ENV NODE_ENV=production

# Default environment variables
ENV CONNECTION_MODE=tcp
ENV SERIAL_PORT=/dev/ttyUSB0
ENV SERIAL_BAUD_RATE=38400
ENV SERIAL_DATA_BITS=8
ENV SERIAL_STOP_BITS=1
ENV SERIAL_PARITY=none
ENV TCP_HOST=192.168.1.100
ENV TCP_PORT=10110
ENV UDP_HOST=192.168.1.100
ENV UDP_PORT=10110
ENV UDP_LISTEN_PORT=10110
ENV WEBSOCKET_SERVER=wss://socket-ais.jasalog.com
ENV DEBOUNCE_DELAY=500
ENV FORWARDER_ENABLED=false
ENV FORWARDER_HOST=0.0.0.0
ENV FORWARDER_PORT=10111
ENV SENDER_ENABLED=true
ENV SENDER_HOST=194.233.93.64
ENV SENDER_PORT=13030
ENV SENDER_RECONNECT_DELAY=500
ENV APP_KEY=your_app_key_here
ENV USER_KEY=your_user_key_here

CMD ["npm", "start"]
